[build]
  builder = "dockerfile"
  dockerfilePath = "Dockerfile"

[deploy]
  startCommand = "node index.js"
  restartPolicyType = "on_failure"
  restartPolicyMaxRetries = 5

[environments.production.variables]
  NODE_ENV = "production"
